package presenters;

public enum Events {
    ADD_PARTITION, ACCEPT_ADD_PARTITION, CANCEL_ADD_PARTITION, ACCEPT_EDIT_PARTITION, CANCEL_EDIT_PARTITION, ADD_PROCESS,
    EDIT_PARTITION, ACCEPT_EDIT_PROCESS, DELETE_PARTITION, CANCEL_EDIT_PROCESS, ACCEPT_ADD_PROCESS, CANCEL_ADD_PROCESS,
    INIT_SIMLATION, EXIT
}

